name: Deploy Dist folder
# on: [push, workflow_dispatch]
on: 
  push: 
    branches:
      - main
      - 'feature/**'
    paths-ignore:
      - README.md
      - '.github/workflows/*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: '2 Github actions/final code'
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        # The line above replaces the lines below, using Github Actions pre created.
        # run: 
        #   echo "cloning repo"
        #   echo "${{toJson(github)}}"
        #   git clone https://github.com/${{github.repository}}.git myfiles
        #   cd myfiles && ls
      - name: setup node js
        uses: ./.github/actions/setupnode
      
      - name: Run Tests
        run: npm run test
      
      - name: Complete job
        run: echo "Test job completed."

  build: 
    needs: test
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: '2 Github actions/final code'
    steps:
      - name: Get Code
        uses: actions/checkout@v4 #Clone repository

      - name: setup node js
        uses: ./.github/actions/setupnode
      
      - name: Build Project
        run: npm run build
      
      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
      
      - name: Complete job
        run: echo "Test job completed."
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: '2 Github actions/final code'
    steps:
      - name: Download Dist Artifact
        uses: actions/download-artifact@v8
        with:
          name: dist-files
          path: dist 

      - name: Deploy Dist
        run: |
          echo "Deploying below files:"
          ls dist
          echo "Deployment completed"
        